---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Setup Archlinux hosts
  hosts: test-cilium-cli-arch
  vars_files:
    - vars/archlinux.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include cilium_cli role
      ansible.builtin.include_role:
        name: githubixx.cilium_cli

- name: Setup Ubuntu hosts
  hosts: test-cilium-cli-ubuntu2004, test-cilium-cli-ubuntu2204
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include cilium_cli role
      ansible.builtin.include_role:
        name: githubixx.cilium_cli
