---
- name: Verify setup
  hosts: all
  vars:
    expected_output: "v0.12"
  tasks:
    - name: Execute cilium version to capture output
      ansible.builtin.command:
        cmd: cilium version
      register: cilium_version_output
      changed_when: false
      environment:
        PATH: "/home/vagrant/.local/bin:{{ ansible_env.PATH }}"

    - name: Ensure cilium version output contains correct version string
      ansible.builtin.assert:
        that:
          - "expected_output in cilium_version_output.stdout"
